version: '3.8'

services:
  api:
    container_name: pokemon-api
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - '.:/usr/src/app'
    ports:
      - '5004:5000'
    environment:
      - FLASK_APP=src/app.py
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@db:5432/test
    depends_on:
      - db

  db:
    container_name: pokemon-db
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres